/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as MuxRouteImport } from './routes/mux'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as FlipflopsRouteImport } from './routes/flipflops'
import { Route as IndexRouteImport } from './routes/index'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MuxRoute = MuxRouteImport.update({
  id: '/mux',
  path: '/mux',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const FlipflopsRoute = FlipflopsRouteImport.update({
  id: '/flipflops',
  path: '/flipflops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flipflops': typeof FlipflopsRoute
  '/gates': typeof GatesRoute
  '/learn': typeof LearnRoute
  '/mux': typeof MuxRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flipflops': typeof FlipflopsRoute
  '/gates': typeof GatesRoute
  '/learn': typeof LearnRoute
  '/mux': typeof MuxRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flipflops': typeof FlipflopsRoute
  '/gates': typeof GatesRoute
  '/learn': typeof LearnRoute
  '/mux': typeof MuxRoute
  '/quiz': typeof QuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flipflops' | '/gates' | '/learn' | '/mux' | '/quiz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flipflops' | '/gates' | '/learn' | '/mux' | '/quiz'
  id: '__root__' | '/' | '/flipflops' | '/gates' | '/learn' | '/mux' | '/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlipflopsRoute: typeof FlipflopsRoute
  GatesRoute: typeof GatesRoute
  LearnRoute: typeof LearnRoute
  MuxRoute: typeof MuxRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mux': {
      id: '/mux'
      path: '/mux'
      fullPath: '/mux'
      preLoaderRoute: typeof MuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flipflops': {
      id: '/flipflops'
      path: '/flipflops'
      fullPath: '/flipflops'
      preLoaderRoute: typeof FlipflopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlipflopsRoute: FlipflopsRoute,
  GatesRoute: GatesRoute,
  LearnRoute: LearnRoute,
  MuxRoute: MuxRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
